
#working_directory = "/home/mark/code/"

[general]
import = [
  # "~/.config/alacritty/themes/themes/autumn.toml"
  "~/.config/alacritty/themes/themes/citylights.toml"
  # "~/.config/alacritty/themes/themes/rose_pine_dawn.toml"
  # "~/.config/alacritty/themes/themes/omni.toml"
  # "~/.config/alacritty/themes/themes/hyper.toml"
]

[window]
dimensions = { columns = 108, lines = 32 }
opacity = 0.8
decorations_theme_variant = "Light"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16
builtin_box_drawing = true

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[cursor]
style = { shape = "Block", blinking = "On"}

[selection]
save_to_clipboard = true
