
#working_directory = "/home/mark/code/"

[window]
dimensions = { columns = 108, lines = 32 }
opacity = 0.8
decorations_theme_variant = "Light"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16
builtin_box_drawing = true

[colors.primary]
foreground = "#f2f2f2"
background = "#000000"

[cursor]
style = { shape = "Block", blinking = "On"}
